---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: srinu225/newrepo:dbimage
   ports:
     - "3306:3306"

 application:
   image: srinu225/newrepo:appimage
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
